bday1=input('Enter birthdate for Steve: ')
bday2=input('Enter birthdate for Jack: ')
bday3=input('Enter birthdate for Icarus: ')
bday4=input('Enter birthdate for Mojo: ')
bday5=input('Enter birthdate for Grover: ')
print(f'Steve, We will wish you on {bday1}')
print(f'Jack, We will wish you on {bday2}')
print(f'Icarus, We will wish you on {bday3}')
print(f'Mojo, We will wish you on {bday4}')
print(f'Grover, We will wish you on {bday5}')