name=input("Enter your name : ")
grade=input("Enter your grade : ")
science=float(input("Enter your marks for science : "))
maths=float(input("Enter your marks for maths : "))
english=float(input("Enter your marks for english : "))
ssc=float(input("Enter your marks for ssc : "))
average=(science+maths+english+ssc)/4
print("Here is your grade report")
print(f"name: {name}")
print(f"grade: {grade}")
print(f"science: {science}")
print(f"maths: {maths}")
print(f"english: {english}")
print(f"ssc: {ssc}")
print(f"average marks: {average}")